### ISSUE TITLE
Can not select serial port

### ISSUE THREAD

**Issue by developer-ken** [github0null/eide#118]
```
[2022/4/29 15:25:16 GMT+0800] : launched
[Error] : enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
Error: enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
    at E.enumSerialPort (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:1:7533)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17098
    at Generator.next (<anonymous>)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9260
    at new Promise (<anonymous>)
    at o (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9005)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17025
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17461
    at m._executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
    at m.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
    at i._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
[Error] : enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
Error: enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
    at E.enumSerialPort (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:1:7533)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17098
    at Generator.next (<anonymous>)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9260
    at new Promise (<anonymous>)
    at o (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9005)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17025
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17461
    at m._executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
    at m.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
    at i._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
[Error] : enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
Error: enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
    at E.enumSerialPort (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:1:7533)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17098
    at Generator.next (<anonymous>)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9260
    at new Promise (<anonymous>)
    at o (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9005)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17025
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17461
    at m._executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
    at m.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
    at i._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
[Error] : enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
Error: enum serialport error !, msg: Unexpected token 锘� in JSON at position 0
    at E.enumSerialPort (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:1:7533)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17098
    at Generator.next (<anonymous>)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9260
    at new Promise (<anonymous>)
    at o (c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:9005)
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17025
    at c:\Users\dengb\.vscode\extensions\cl.eide-3.5.0\dist\extension.js:7:17461
    at m._executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30760)
    at m.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:31302)
    at i._doInvokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13826)
    at i._invokeHandler (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13510)
    at i._receiveRequest (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12171)
    at i._receiveOneMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10841)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8947
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34275
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at d.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19034)
    at o._receiveMessage (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23615)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21149
    at u.invoke (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
    at v.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
    at v.acceptChunk (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15865)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14995
    at Socket.P (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13797)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

```

**Comment by github0null** [comment]
window 系统代码页不要弄成 utf8 了，换成 gbk，会有 bom 头，导致 json 无法被解析
